### ISSUE TITLE
CSS Entries are not deleted when deleting snippet in SW6 backend

### ISSUE THREAD

**Issue by fowado** [dneustadt/DneCustomCssJs#3]
title

**Comment by dneustadt** [comment]
Thank you for your notice. I looked into the issue and was reminded that it exists in the first place due to some missing extension points in the Shopware administration.
I created a PR https://github.com/shopware/platform/pull/1462 that will enable me to have the plugin recompile the theme after a container gets deleted. Once that PR gets merged and released I will follow up with an update of the plugin.
In the meantime you can delete all containers, create a new one, leave it empty and recompile the theme. That will eliminate any custom code left and will have to do as a workaround as for now.

**Comment by fowado** [comment]
without such a basic event there is nothing to update then. Thank you very much for your solution as well as the great plugin.
